from ml.config import (
    REAL_ENV_FEATURE_COLUMNS,
    REAL_NUCLIDE_FEATURE_COLUMNS,
    REAL_TARGET_COLUMN,
)


REQUIRED_REAL_COLUMNS = set(REAL_NUCLIDE_FEATURE_COLUMNS + [REAL_TARGET_COLUMN])
OPTIONAL_REAL_COLUMNS = set(REAL_ENV_FEATURE_COLUMNS)
ALLOWED_ADVANCED_OVERRIDES = set(REAL_NUCLIDE_FEATURE_COLUMNS + REAL_ENV_FEATURE_COLUMNS)
